name: manual_ci

on:
  workflow_dispatch:


jobs:
  build:
    name: manual-tests
    runs-on: ubuntu-latest
    steps:
      - name: print information
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.head_ref }}"

      - name: checkout to branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install --only-binary=numba --only-binary=llmvlite -r requirements_dev.txt
          pip install .[dev] --no-deps
          
      - name: execute pytest
        run: pytest
